services:
  openchronicle:
    build: .
    entrypoint: ["oc"]
    environment:
      - OC_DB_PATH=/data/openchronicle.db
      - OC_CONFIG_DIR=/config
      - OC_PLUGIN_DIR=/plugins
    env_file:
      - .env
    volumes:
      - "C:/microSD/Docker/data:/data"
      - "C:/microSD/Docker/config:/config"
      - "C:/microSD/Docker/plugins:/plugins"
