"""Backward-compatible re-export of canonical error code constants."""

from __future__ import annotations

from openchronicle.core.domain.errors import error_codes as _codes

INVALID_ARGUMENT = _codes.INVALID_ARGUMENT
INVALID_REQUEST = _codes.INVALID_REQUEST
INVALID_TASK_TYPE = _codes.INVALID_TASK_TYPE
INVALID_JSON = _codes.INVALID_JSON
UNKNOWN_HANDLER = _codes.UNKNOWN_HANDLER
UNKNOWN_TASK_TYPE = _codes.UNKNOWN_TASK_TYPE
UNKNOWN_COMMAND = _codes.UNKNOWN_COMMAND
PROJECT_NOT_FOUND = _codes.PROJECT_NOT_FOUND
TASK_NOT_FOUND = _codes.TASK_NOT_FOUND
UNSUPPORTED_PROTOCOL_VERSION = _codes.UNSUPPORTED_PROTOCOL_VERSION
INTERNAL_ERROR = _codes.INTERNAL_ERROR
HANDLER_ERROR = _codes.HANDLER_ERROR
HANDLER_COLLISION = _codes.HANDLER_COLLISION
PLUGIN_ID_COLLISION = _codes.PLUGIN_ID_COLLISION
PLUGIN_COLLISION = _codes.PLUGIN_COLLISION
OUTBOUND_PII_BLOCKED = _codes.OUTBOUND_PII_BLOCKED
NSFW_POOL_NOT_CONFIGURED = _codes.NSFW_POOL_NOT_CONFIGURED
SELF_REPORT_INVALID = _codes.SELF_REPORT_INVALID
PROVIDER_REQUIRED = _codes.PROVIDER_REQUIRED
PROVIDER_NOT_CONFIGURED = _codes.PROVIDER_NOT_CONFIGURED
INVALID_PROVIDER = _codes.INVALID_PROVIDER
MISSING_API_KEY = _codes.MISSING_API_KEY
MISSING_PACKAGE = _codes.MISSING_PACKAGE
CLIENT_MISSING = _codes.CLIENT_MISSING
CONFIG_ERROR = _codes.CONFIG_ERROR
PROVIDER_ERROR = _codes.PROVIDER_ERROR
UNEXPECTED_ERROR = _codes.UNEXPECTED_ERROR
BUDGET_EXCEEDED = _codes.BUDGET_EXCEEDED
TIMEOUT = _codes.TIMEOUT
CONNECTION_ERROR = _codes.CONNECTION_ERROR
UNKNOWN_ERROR = _codes.UNKNOWN_ERROR

__all__ = [
    "INVALID_ARGUMENT",
    "INVALID_REQUEST",
    "INVALID_TASK_TYPE",
    "INVALID_JSON",
    "UNKNOWN_HANDLER",
    "UNKNOWN_TASK_TYPE",
    "UNKNOWN_COMMAND",
    "PROJECT_NOT_FOUND",
    "TASK_NOT_FOUND",
    "UNSUPPORTED_PROTOCOL_VERSION",
    "INTERNAL_ERROR",
    "HANDLER_ERROR",
    "HANDLER_COLLISION",
    "PLUGIN_ID_COLLISION",
    "PLUGIN_COLLISION",
    "OUTBOUND_PII_BLOCKED",
    "NSFW_POOL_NOT_CONFIGURED",
    "SELF_REPORT_INVALID",
    "PROVIDER_REQUIRED",
    "PROVIDER_NOT_CONFIGURED",
    "INVALID_PROVIDER",
    "MISSING_API_KEY",
    "MISSING_PACKAGE",
    "CLIENT_MISSING",
    "CONFIG_ERROR",
    "PROVIDER_ERROR",
    "UNEXPECTED_ERROR",
    "BUDGET_EXCEEDED",
    "TIMEOUT",
    "CONNECTION_ERROR",
    "UNKNOWN_ERROR",
]
