"""Canonical error code constants for core + interfaces."""

from __future__ import annotations

# Request / validation
INVALID_ARGUMENT = "INVALID_ARGUMENT"
INVALID_REQUEST = "INVALID_REQUEST"
INVALID_TASK_TYPE = "INVALID_TASK_TYPE"
INVALID_JSON = "INVALID_JSON"
UNKNOWN_HANDLER = "UNKNOWN_HANDLER"
UNKNOWN_TASK_TYPE = "UNKNOWN_TASK_TYPE"
UNKNOWN_COMMAND = "UNKNOWN_COMMAND"
PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
TASK_NOT_FOUND = "TASK_NOT_FOUND"
JOB_NOT_FOUND = "JOB_NOT_FOUND"
INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
UNSUPPORTED_PROTOCOL_VERSION = "UNSUPPORTED_PROTOCOL_VERSION"
INTERNAL_ERROR = "INTERNAL_ERROR"

# Task execution / handler
HANDLER_ERROR = "HANDLER_ERROR"
HANDLER_COLLISION = "HANDLER_COLLISION"
PLUGIN_ID_COLLISION = "PLUGIN_ID_COLLISION"
PLUGIN_COLLISION = "PLUGIN_COLLISION"

# Privacy / routing
OUTBOUND_PII_BLOCKED = "OUTBOUND_PII_BLOCKED"
NSFW_POOL_NOT_CONFIGURED = "NSFW_POOL_NOT_CONFIGURED"
SELF_REPORT_INVALID = "SELF_REPORT_INVALID"

# MoE execution
MOE_INSUFFICIENT_EXPERTS = "MOE_INSUFFICIENT_EXPERTS"

# Capability-aware routing
NO_CAPABLE_MODEL = "NO_CAPABLE_MODEL"

# Provider selection / configuration (existing provider error codes)
PROVIDER_REQUIRED = "provider_required"
PROVIDER_NOT_CONFIGURED = "provider_not_configured"
INVALID_PROVIDER = "invalid_provider"
MISSING_API_KEY = "missing_api_key"
MISSING_PACKAGE = "missing_package"
CLIENT_MISSING = "client_missing"
CONFIG_ERROR = "config_error"
PROVIDER_ERROR = "provider_error"
UNEXPECTED_ERROR = "unexpected_error"
BUDGET_EXCEEDED = "budget_exceeded"

# Transport/runtime (existing provider error codes)
TIMEOUT = "timeout"
CONNECTION_ERROR = "connection_error"
UNKNOWN_ERROR = "unknown"

__all__ = [
    "INVALID_ARGUMENT",
    "INVALID_REQUEST",
    "INVALID_TASK_TYPE",
    "INVALID_JSON",
    "UNKNOWN_HANDLER",
    "UNKNOWN_TASK_TYPE",
    "UNKNOWN_COMMAND",
    "PROJECT_NOT_FOUND",
    "TASK_NOT_FOUND",
    "JOB_NOT_FOUND",
    "INVALID_STATE_TRANSITION",
    "UNSUPPORTED_PROTOCOL_VERSION",
    "INTERNAL_ERROR",
    "HANDLER_ERROR",
    "HANDLER_COLLISION",
    "PLUGIN_ID_COLLISION",
    "PLUGIN_COLLISION",
    "OUTBOUND_PII_BLOCKED",
    "NSFW_POOL_NOT_CONFIGURED",
    "SELF_REPORT_INVALID",
    "MOE_INSUFFICIENT_EXPERTS",
    "NO_CAPABLE_MODEL",
    "PROVIDER_REQUIRED",
    "PROVIDER_NOT_CONFIGURED",
    "INVALID_PROVIDER",
    "MISSING_API_KEY",
    "MISSING_PACKAGE",
    "CLIENT_MISSING",
    "CONFIG_ERROR",
    "PROVIDER_ERROR",
    "UNEXPECTED_ERROR",
    "BUDGET_EXCEEDED",
    "TIMEOUT",
    "CONNECTION_ERROR",
    "UNKNOWN_ERROR",
]
